### ISSUE TITLE
Push a segwit tx got 500 error from api but still broadcasted 

### ISSUE THREAD

**Issue by DuanTranHuy** [haskoin/haskoin-store#25] opened 2021-09-16 08:19 UTC
Hi,

I sign an offline segwit tx then broadcast this one but got 500 internal error. But the TX still broadcasted and get confirm after that. This is txhash [60f01e25f0f63ccdfe2fc364298f7a148e45d4d06248648055c094467258932c](https://www.blockchain.com/btc-testnet/tx/60f01e25f0f63ccdfe2fc364298f7a148e45d4d06248648055c094467258932c)

**Comment by jprupp** [comment] 2022-02-13 17:30
Yes, I'm still not sure what the best way to go about this is.

**Comment by jprupp** [comment] 2022-02-14 14:09
I guess if you get an error that is ambiguous, you should retry sending the transaction. This is idempotent. The same transaction will succeed on the second try if the network accepted the first broadcast, and the Haskoin Store node received it from a peer and indexed it.

**Comment by veado** [comment] 2022-02-15 20:02
Same issue here: Tried re-sending a same transaction up to 5 times in an interval of 0.5 sec, but got a `500`. Sometimes it works, sometimes not. It's like a lottery. 

From logs:
```
[Error#Web] POST /transactions HTTP/1.1 [...]: 500 Internal Server Error @(haskoin-store-0.53.11-H3lIG36UX3334wJLQ6F8RO:Haskoin.Store.Web src/Haskoin/Store/Web.hs:2665:37)
```

Any chance to get it fixed on Haskoin side?

**Comment by jp-sif** [comment] 2022-02-19 09:32
I'll change the algoritm such that it:

- sends transaction to all connected peers; and
- responds with 200 OK.

No validity checks or errors will be returned. It is up to the client to send a valid transaction with sufficient fees.

Change will go live in about two weeks because there has been a non-backwards-compatible change to the database and it hasn't finished synchronising the block chain yet.

**Comment by petergombos** [comment] 2022-02-19 09:38
Would we get the txid back after the broadcast? One could use that to try to fetch the transaction to see if it was successful. Also after a successful broadcast can one expect that the utxos will be up to date right after the call? I would like to refresh the balance of an address and send it back to the client.

**Comment by jp-sif** [comment] 2022-02-19 11:09
The issue is the Bitcoin protocol, which is both asynchronous and stateful. If I send a transaction to a peer, and it gets accepted, I get no answer. If it gets rejected, I get a rejection message. If I attempt to send it again, I get nothing. It's a black hole.

My code tries to account for this. It waits for a short timeout to see whether the transaction ends up indexed or rejected, but it doesn't cache rejections. If a transaction gets rejected once, the user gets the rejection status back. If the user tries again, a 500 error is returned instead because there will be no more reject messages from the network peer, unless the rejection was caught by Haskoin Store directly before attempting to broadcast the transaction.

**Comment by jprupp** [comment] 2022-02-19 11:11
The issue is the Bitcoin protocol, which is both asynchronous and stateful. If I send a transaction to a peer, and it gets accepted, I get no answer. If it gets rejected, I get a rejection message. If I attempt to send it again, I get nothing. It's a black hole.

My code tries to account for this. It waits for a short timeout to see whether the transaction ends up indexed or rejected, but it doesn't cache rejections. If a transaction gets rejected once, the user gets the rejection status back. If the user tries again, a 500 error is returned instead because there will be no more reject messages from the network peer, unless the rejection was caught by Haskoin Store directly before attempting to broadcast the transaction.

**Closed** 2023-10-03 14:41 UTC
Labels: bug
